return {
	"ThePrimeagen/harpoon",
	branch = "harpoon2",
	dependencies = { "nvim-lua/plenary.nvim" },
	config = function()
		local harpoon = require("harpoon")
		harpoon:setup()

		local remap = vim.keymap.set
		remap("n", "<leader>a", function()
			harpoon:list():append()
		end, { desc = "Harpoon: append buffer" })
		remap("n", "<leader><space>", function()
			harpoon.ui:toggle_quick_menu(harpoon:list())
		end, { desc = "Harpoon: toggle quick menu" })

		remap("n", "<leader>1", function()
			harpoon:list():select(1)
		end, { desc = "Harpoon: select first buffer" })
		remap("n", "<leader>2", function()
			harpoon:list():select(2)
		end, { desc = "Harpoon: select second buffer" })
		remap("n", "<leader>3", function()
			harpoon:list():select(3)
		end, { desc = "Harpoon: select third buffer" })
		remap("n", "<leader>4", function()
			harpoon:list():select(4)
		end, { desc = "Harpoon: select fourth buffer" })
		remap("n", "<leader>5", function()
			harpoon:list():select(5)
		end, { desc = "Harpoon: select fifth buffer" })
		remap("n", "<leader>6", function()
			harpoon:list():select(6)
		end, { desc = "Harpoon: select sixth buffer" })
		remap("n", "<leader>7", function()
			harpoon:list():select(7)
		end, { desc = "Harpoon: select seventh buffer" })
		remap("n", "<leader>8", function()
			harpoon:list():select(8)
		end, { desc = "Harpoon: select eigth buffer" })
		remap("n", "<leader>9", function()
			harpoon:list():select(9)
		end, { desc = "Harpoon: select ninth buffer" })
		remap("n", "<leader>0", function()
			harpoon:list():select(0)
		end, { desc = "Harpoon: select tenth buffer" })

		remap("n", "<C-S->>", function()
			harpoon:list():next()
		end, { desc = "Harpoon: select next buffer" })
		remap("n", "<C-S-<>", function()
			harpoon:list():prev()
		end, { desc = "Harpoon: select previous buffer" })
		remap("n", "<leader>q", function()
			harpoon:list():remove()
		end, { desc = "Harpoon: removes current buffer from list" })
		remap("n", "<leader>cc", function()
			harpoon:list():clear()
		end, { desc = "Harpoon: clear list" })
	end,
}
