local opts = {
	nu = true,
	rnu = true,
	expandtab = true,
	tabstop = 2,
	softtabstop = 2,
	shiftwidth = 2,
	wrap = false,
	autoindent = true,
	smartindent = true,
	breakindent = true,
	cursorline = true,
	ignorecase = true,
	smartcase = true,
	backup = false,
	undofile = false,
	undodir = os.getenv("HOME") .. "./vim/undodiir",
	hlsearch = true,
	incsearch = true,
	termguicolors = true,
	signcolumn = "yes",
	ttimeoutlen = 300,
	completeopt = "menu,menuone,noinsert,noselect",
	autochdir = false,
	confirm = false,
	splitright = true,
	splitbelow = true,
	foldmethod = "manual",
	foldlevel = 99,
	scrolloff = 4,
	sidescrolloff = 4,
	updatetime = 200,
	virtualedit = "block",
	clipboard = "unnamedplus",
	swapfile = false,
}

for k, v in pairs(opts) do
	vim.opt[k] = v
end
